services:
  - type: web
    name: todolist
    env: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails s -p 3000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todolist-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production

databases:
  - name: todolist-db
    plan: free
    ipAllowList: []