default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { '' } %>

development:
  <<: *default
  database: todolist_development

test:
  <<: *default
  database: todolist_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: todolist_production
  username: todolist
  password: <%= ENV['DATABASE_PASSWORD'] %>